##############################################################################
# Copyright (c) 2017 Orange and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
### vPOD descriptor file ###

details:
  pod_owner: ONAPatDT
  contact: N/A
  lab: ONAP Darmstadt
  location: N/A
  type: testing
  link: http://wiki.onap.org/
##############################################################################

nodes:
  - name: jumphost1
    node: &nodeparams
      flavor: "m1.medium"
      model: Ubuntu_1804
      type: virtual
      vendor: openstack
      arch: x86_64
      cpus: 4
      cpu_cflags: host-model
      cores: 8
      memory: 8G
    disks: &disks
      - name: disk1
        disk_capacity: 40G
        disk_type: qcow2
        disk_interface: ide
        disk_rotation:
    remote_management: &remote_management
      type:
        - ipmi: NA
      user: NA
      pass: NA
      address: NA
      mac_address: NA
    interfaces: &interfaces
      - mac_address:
        name: nic1
        speed:
        features:

#  - name: pod-test-jumphost
#    node: &nodeparams
#      type: virtual
#      vendor: openstack
#      model: Ubuntu_1804
#      arch: x86_64
#      cpus: 4
#      cpu_cflags: host-model
#      cores: 8
#      memory: 8G
#    disks: &disks
#      - name: disk1
#        disk_capacity: 40G
#        disk_type: qcow2
#        disk_interface: ide
#        disk_rotation:
#    remote_management: &remote_management
#      type:
#        - ipmi: NA
#      user: NA
#      pass: NA
#      address: NA
#      mac_address: NA
#    interfaces: &interfaces
#      - mac_address:
#        name: nic1
#        speed:
#        features:
