// Generated by init.sh
var gitlabUrl = ;
var chainedCiProjectId = ;
var scenarioFolder = ;
var chainedCiUrl = ;
var rootUrl = ;
var gitlabCiFilename = ;
var pipelines_size = ;
var updateTimer = 60;
var tokenTargets = [];
var optimizedRefreshLevel = 5;

// tool url
var gitlabCiFile = gitlabCiFilename;
var gitlabApi = gitlabUrl+'api/v4/projects/';
var gitlabProfileToken = '/profile/personal_access_tokens';
